### ISSUE TITLE
Pywrap documentation and sample application

### ISSUE THREAD

**Issue by ZongHong-Lyu** [DigitalMediaProfessionals/dv-sdk#1]
The pywrap pull request is merged to the master branch.
But the wiki documentations are not added yet.

Please add one page about how to use the python wrapper. The environment setup page should also be updated to include 'jinja2' module as necessary module.

And I think maybe it is better to add one sample of using the python wrapper and run the network from python on FPGA. Please add one sample based on mobilenet to the 'application' repository.

**Comment by YuyaKobayashi** [comment]
Lyu-san,

Could you review [Python Wrapper](https://github.com/DigitalMediaProfessionals/dv-sdk/wiki/Python-Wrapper-Usage)?

After the review, I will translate it into Japanese.

**Comment by YuyaKobayashi** [comment]
About sample code, I created an issue in **application** repository.

**Comment by ZongHong-Lyu** [comment]
Kobayashi-san,

I've followed the instructions on the wiki page, but I met the following issues:

1. In the `How to Build` section, the 4th step, I need to add the following link flags, else the `import gnet_wrap` will fail:
```
 -ldmpdv -lboost_python3 -lboost_numpy3 
```

2. In the `Simple Sample` section, the sample code has many typos: `initalize` should be `initialize`, `load_weight` should be `load_weights`

3. The line `gnw.load_weights("path/to/DV_weight.bin/")` fails with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
LookupError: unknown encoding: utfi
>>> gnw.load_weights(weight_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    gnet_wrap.load_weights(str)
did not match C++ signature:
    load_weights(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```
I can't find a way to solve it so I give up there.

**Comment by YuyaKobayashi** [comment]
Thank you Lyu-san,

>1.
You might need to install Boost.Python, Boost.Numpy.
Run `apt install libboost-numpy-dev libpython3.6-dev`.

>2.
fixed

>3.
I have to see the code

**Comment by ZongHong-Lyu** [comment]
Kobayashi-san,

About 1, I already installed the two packages you mentioned, but I still need to set link flag as I said in my previous comment.

And I can successfully run the sample now. There are just some minor bugs:
1. you missed `import numpy as np` in the sample code
2. the `get_conv_fc_usec` should be `get_fc_usec`

Besides, the C++ version of `get_final_output` actually accepts one optional parameter `int id`, which if not given default to be 0. In some networks there might be more than one output layers, so to get the result of those layers, it is necessary to pass `id > 0`. But I think this should be handle by another issue.

**Comment by YuyaKobayashi** [comment]
Thank you Lyu-san,

I reflected all your suggestions

**Comment by YuyaKobayashi** [comment]
I created a new issue about the get_final_output() problem

**Comment by YuyaKobayashi** [comment]
Thank you

I added the flag.

I will translate

**Comment by YuyaKobayashi** [comment]
I created Japanese page.

Review will be done in the overall review of Japanese pages before the deliver.
So I close this issue.
